"use strict";
const URL_SB="https://ewvmwgsgwpkwycaqdgir.supabase.co", KEY_SB="sb_publishable_BA4Sts6N3tHG__HL4G02jw_dyiIt8kL", SESION_KEY="xv_admin_session";
const login=document.getElementById("loginAdmin"),dashboard=document.getElementById("dashboard"),loginEstado=document.getElementById("loginEstado"),estadoGlobal=document.getElementById("estadoGlobal");
let sesion=null,familias=[],lector=null,folioActual=null;
async function autenticar(email,password){
  const r=await fetch(`${URL_SB}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:KEY_SB,"Content-Type":"application/json"},body:JSON.stringify({email,password})});
  const d=await r.json().catch(()=>({}));
  if(!r.ok){
    const codigo=d.error_code||d.code||"";
    const detalle=d.msg||d.error_description||d.message||"";
    if(codigo==="email_not_confirmed"||/confirm/i.test(detalle))throw new Error("Falta confirmar el correo en Supabase Authentication.");
    if(codigo==="invalid_credentials"||r.status===400)throw new Error("El correo o la contraseña no coinciden.");
    throw new Error(`No fue posible iniciar sesión (${r.status}). ${detalle}`.trim());
  }
  return d;
}
async function rpc(nombre,body={}){if(!sesion?.access_token)throw new Error("Sesión no disponible.");const r=await fetch(`${URL_SB}/rest/v1/rpc/${nombre}`,{method:"POST",headers:{apikey:KEY_SB,Authorization:`Bearer ${sesion.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message||"No fue posible consultar el sistema.");return d}
async function entrar(s){sesion=s;const admin=await rpc("es_administrador");if(!admin)throw new Error("La cuenta existe, pero todavía no está autorizada como administradora.");sessionStorage.setItem(SESION_KEY,JSON.stringify(s));login.hidden=true;dashboard.hidden=false;await cargarPanel()}
document.getElementById("formLogin").addEventListener("submit",async e=>{e.preventDefault();loginEstado.textContent="Verificando acceso…";try{await entrar(await autenticar(e.target.email.value.trim(),e.target.password.value));loginEstado.textContent=""}catch(err){loginEstado.textContent=err.message}});
async function cargarPanel(){estadoGlobal.textContent="Actualizando información…";try{const [r,f]=await Promise.all([rpc("admin_resumen"),rpc("admin_listar_familias")]);familias=f;renderResumen(r);renderFamilias(f);estadoGlobal.textContent=`Actualizado ${new Date().toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"})}`}catch(e){estadoGlobal.textContent=e.message}}
function renderResumen(r){const datos=[["Familias",r.familias_total],["Confirmadas",r.familias_confirmadas],["Pendientes",r.familias_pendientes],["No asistirán",r.familias_no_asisten],["Boletos asignados",r.boletos_asignados],["Invitados",r.invitados_confirmados],["Adultos",r.adultos],["Menores",r.menores],["Entradas registradas",r.boletos_utilizados]];document.getElementById("metricas").innerHTML=datos.map(x=>`<article class="metrica"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join("");const nombres={sin_alcohol:"Sin alcohol",sin_elegir:"Sin elegir",menor:"Menores"};document.getElementById("bebidas").innerHTML=Object.entries(r.bebidas||{}).map(([k,v])=>`<div class="bebida"><strong>${v}</strong><span>${nombres[k]||k}</span></div>`).join("")||"<p>Sin selecciones registradas.</p>"}
function renderFamilias(lista){document.getElementById("tablaFamilias").innerHTML=lista.map(f=>`<tr><td><strong>${esc(f.familia)}</strong><br><small>${esc(f.codigo)}</small></td><td><span class="estado-chip">${esc(f.estado)}</span></td><td>${f.registrados} / ${f.boletos_maximos}</td><td><div class="invitados-mini">${f.invitados.map(i=>`<span>${esc(i.nombre)} <small>· ${esc(i.tipo)} · ${esc(i.bebida||"sin elegir")} · ${esc(i.folio)}${i.utilizado?" · ENTRÓ":""}</small></span>`).join("")||"<small>Sin registros</small>"}</div></td></tr>`).join("")}
function esc(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}
document.getElementById("buscarInvitado").addEventListener("input",e=>{const q=e.target.value.toLowerCase().trim();renderFamilias(!q?familias:familias.filter(f=>JSON.stringify(f).toLowerCase().includes(q)))});
document.querySelectorAll("[data-tab]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("activo",x===b));document.querySelectorAll(".vista").forEach(v=>{v.hidden=v.id!==`tab-${b.dataset.tab}`;v.classList.toggle("activo",!v.hidden)})}));
document.getElementById("actualizarPanel").addEventListener("click",cargarPanel);document.getElementById("cerrarSesion").addEventListener("click",()=>{sessionStorage.removeItem(SESION_KEY);location.reload()});
document.getElementById("exportarCSV").addEventListener("click",()=>{const filas=[["Familia","Estado","Código","Boletos asignados","Invitado","Tipo","Bebida","Folio","Entrada"]];familias.forEach(f=>(f.invitados.length?f.invitados:[{}]).forEach(i=>filas.push([f.familia,f.estado,f.codigo,f.boletos_maximos,i.nombre||"",i.tipo||"",i.bebida||"",i.folio||"",i.utilizado?"Sí":"No"])));const csv="\ufeff"+filas.map(f=>f.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="invitados-xv-lizzeth.csv";a.click();URL.revokeObjectURL(a.href)});
async function validar(folio,marcar=false){const d=await rpc("admin_validar_boleto",{p_folio:folio,p_marcar_entrada:marcar});folioActual=d.folio||folio;const box=document.getElementById("resultadoBoleto");box.hidden=false;box.classList.toggle("error",!d.ok);document.getElementById("resultadoIcono").textContent=d.ok?"✓":"!";document.getElementById("resultadoTitulo").textContent=d.mensaje;document.getElementById("resultadoDetalle").textContent=d.nombre?`${d.nombre} · ${d.familia} · ${d.folio}`:"Revisa el folio e intenta nuevamente.";document.getElementById("registrarEntrada").hidden=!d.ok||marcar;if(marcar)await cargarPanel()}
document.getElementById("formFolio").addEventListener("submit",async e=>{e.preventDefault();try{await validar(document.getElementById("folioManual").value.trim())}catch(err){estadoGlobal.textContent=err.message}});document.getElementById("registrarEntrada").addEventListener("click",()=>validar(folioActual,true).catch(e=>estadoGlobal.textContent=e.message));
document.getElementById("iniciarEscaner").addEventListener("click",async()=>{if(!window.Html5Qrcode){estadoGlobal.textContent="No se pudo cargar el lector QR.";return}try{lector=new Html5Qrcode("lectorQR");document.getElementById("iniciarEscaner").hidden=true;document.getElementById("detenerEscaner").hidden=false;await lector.start({facingMode:"environment"},{fps:10,qrbox:{width:230,height:230}},async texto=>{await detener();document.getElementById("folioManual").value=texto;await validar(texto)})}catch(e){estadoGlobal.textContent="No fue posible abrir la cámara. Revisa el permiso del navegador."}});
async function detener(){if(lector){try{await lector.stop();await lector.clear()}catch{}lector=null}document.getElementById("iniciarEscaner").hidden=false;document.getElementById("detenerEscaner").hidden=true}document.getElementById("detenerEscaner").addEventListener("click",detener);
try{const guardada=JSON.parse(sessionStorage.getItem(SESION_KEY));if(guardada)entrar(guardada).catch(()=>sessionStorage.removeItem(SESION_KEY))}catch{}
